### ISSUE TITLE
Make 2 new repositories - CMS-Core & CMS-Server

### ISSUE THREAD

**Issue by rohan23chhabra** [DevourTech/Course-Management-System#2]
2 new repositories need to be added to the CMS project.
This will ensure decoupling and reusability of modules.

For all core functionality => CMS-Core
For server => CMS-Server

Also, explore the versioning of Java modules (JARs) and releasing them on the maven repository to be consumed by client and server.

**Comment by archit-1997** [comment]
### Two new repositories have been created and linked to the project CMS . 

1. CMS Core
2. CMS Server
